---
gnome_configuration:
  - {key: desktop/interface/gtk-theme, value: "'Yaru-dark'"}
  - {key: shell/extensions/dash-to-dock/dock-fixed, value: "false"}
  - {key: desktop/notifications/show-in-lock-screen, value: "false"}
  - {key: desktop/search-providers/disable-external, value: "true"}
  - {key: settings/file-chooser/show-hidden, value: "false"}
  - {
    key: desktop/input-sources/sources,
    value: "[('xkb', 'us'), ('xkb', 'ru')]"
  }
  - {key: desktop/privacy/remember-recent-files, value: "false"}
  - {key: desktop/screensaverlock-delay/lock-delay, value: "uint32 0"}
  - {key: desktop/session/idle-delay, value: "uint32 900"}
  - {
    key: settings-daemon/plugins/power/sleep-inactive-ac-timeout,
    value: "3600"
  }
  - {
    key: settings-daemon/plugins/power/sleep-inactive-ac-type,
    value: "'nothing'"
  }

shortcuts:
  - {
    key: custom0,
    values: [
      {name: "binding", value: "'<Primary><Alt>n'"},
      {name: "command", value: "'/usr/bin/nautilus'"},
      {name: "name", value: "'nautilus'"}
    ]
  }
  - {
    key: custom1,
    values: [
      {name: "binding", value: "'<Primary><Alt>f'"},
      {name: "command", value: "'/usr/bin/firefox'"},
      {name: "name", value: "'firefox'"}
    ]
  }
  - {
    key: custom2,
    values: [
      {name: "binding", value: "'<Primary><Alt>c'"},
      {name: "command", value: "'/usr/bin/chromium-browser'"},
      {name: "name", value: "'chromium-browser'"}
    ]
  }
  - {
    key: custom3,
    values: [
      {name: "binding", value: "'<Primary><Alt>e'"},
      {name: "command", value: "'/usr/bin/code-insiders'"},
      {name: "name", value: "'code-insiders'"}
    ]
  }
  - {
    key: custom4,
    values: [
      {name: "binding", value: "'<Primary><Alt>v'"},
      {name: "command", value: "'/usr/bin/VirtualBox'"},
      {name: "name", value: "'VirtualBox'"}
    ]
  }